name: Manage Milestones

on:
  # It's recommended to change the schedule to something that works for
  # your process. Conduit will run this once a week on Friday to
  # coincide with the weekly 'whos going to work on what' meeting.
  # You could remove schedule all together and only trigger this manually.
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # we want the check for milestone management to only happen on work
    # days.
    - cron:  '0 0 * * 6'
  workflow_dispatch:

jobs:
  milestones:
    uses: hariso/automation/.github/workflows/milestones.yml@main
    with:
      org-repo: 'hariso/automation'
      project: PVT_kwHOACEOHM4AL0cO
    secrets:
      project-automation-token: ${{ secrets.PROJECT_AUTOMATION }}