name: project-management

on:
  workflow_call:
    inputs:
      project:
        description: 'Node id of the Org-level Beta project'
        default: PVT_kwHOACEOHM4AL0cO
        required: false
        type: string
    secrets:
      project-automation-token:
        required: true

jobs:
  triage_new_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Main
        env:
          GITHUB_TOKEN: ${{ secrets.project-automation-token }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: ${{ inputs.project }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID )"
