name: roadmap-automation

on:
  workflow_call:
    inputs:
      project:
        description: 'Node id of the Org-level Beta project for Roadmaps'
        default: PVT_kwDOBL3ZPs4AAigJ
        required: false
        type: string
    secrets:
      project-automation-token:
        required: true

jobs:
  add_to_roadmap:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'roadmap')
    steps:
      # note that if the item was already on the roadmap we
      # get an error from the api. that's ok.
      - name: Add to Roadmap
        env:
          GITHUB_TOKEN: ${{ secrets.project-automation-token }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: ${{ inputs.project }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID )"

  remove_from_roadmap:
    runs-on: ubuntu-latest
    if: github.event.action == 'unlabeled' && (contains(github.event.issue.labels.*.name, 'roadmap') == false)
    steps:
      - name: Remove from Roadmap
        uses: conduitio/automation/actions/remove_issue_from_project@main
        with:
          project: ${{ inputs.project }}
          issue-node-id: ${{ github.event.issue.node_id }}
          repo-token: ${{ secrets.project-automation-token }}

